services:
  database:
    image: mysql
    container_name: db_staging
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: eep-db-staging
      MYSQL_PASSWORD: MySql@123
      MYSQL_DATABASE: wayshub
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - eep_network

  migration:
    build:
      context: ./wayshub-backend
      dockerfile: Dockerfile
    container_name: migration_staging
    command: >
      sh -c "sequelize db:migrate"
    environment:
      NODE_ENV: staging
      DB_HOST: database
      DB_USER: eep-db-staging
      DB_PASSWORD: MySql@123
      DB_NAME: wayshub
    depends_on:
      - database
    networks:
      - eep_network

  backend:
    build:
      context: ./wayshub-backend
      dockerfile: Dockerfile
    container_name: wayshub-backend_staging
    restart: always
    environment:
      NODE_ENV: staging
      DB_HOST: database
      DB_USER: eep-db-staging
      DB_PASSWORD: MySql@123
      DB_NAME: wayshub
    depends_on:
      - database
    networks:
      - eep_network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./wayshub-frontend
      dockerfile: Dockerfile
    container_name: wayshub-frontend_staging
    restart: always
    networks:
      - eep_network
    ports:
      - "3000:3000"

  webserver:
    image: nginx:alpine
    container_name: webserver_staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - eep_network

  certbot:
    image: certbot/certbot
    container_name: certbot_staging
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
    entrypoint: >
      sh -c "
      certbot certonly --webroot -w /var/www/certbot \
      -d eep.staging.studentdumbways.my.id \
      -d api.eep.staging.studentdumbways.my.id \
      --email purwanto.edy.eko@gmail.com \
      --agree-tos --non-interactive && \
      nginx -s reload && \
      while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done
      "
    depends_on:
      - webserver
    networks:
      - eep_network

volumes:
  db_staging:

networks:
  eep_network:
    driver: bridge